#! /bin/sh

# Update configuration from environment variables

if [ "$MY_HOSTNAME" ]; then
  echo "$MY_HOSTNAME" > /etc/mailname
  postconf -e myhostname="$MY_HOSTNAME"
fi

if [ "$MY_NETWORKS" ]; then
  postconf -e mynetworks="$MY_NETWORKS"
fi

if [ "$MY_DESTINATION" ]; then
  postconf -e mydestination="$MY_DESTINATION"
fi

if [ "$VIRTUAL_ALIAS_DOMAINS" ]; then
  postconf -e mydestination=localhost
  postconf -e virtual_alias_domains="$VIRTUAL_ALIAS_DOMAINS"
  postconf -e virtual_alias_maps="hash:/etc/postfix/virtual"
  postmap /etc/postfix/virtual
fi

if [ "$ROOT_ALIAS" ]; then
  sed -i '/^root:/d' /etc/aliases
  echo "root: $ROOT_ALIAS" >> /etc/aliases
  newaliases
fi


# Since postfix default logs to syslog we will need to redirect it
postconf -e maillog_file=/var/log/mail.log

touch /var/log/mail.log

/usr/sbin/postfix start 

tail -fn 0 /var/log/mail.log 

exit 0

