#! /bin/sh

if [ "$MY_HOSTNAME" ]; then
  echo "$MY_HOSTNAME" > /etc/mailname
  postconf -e myhostname="$MY_HOSTNAME"
fi

if [ "$MY_NETWORKS" ]; then
  postconf -e mynetworks="$MY_NETWORKS"
fi

if [ "$MY_DESTINATION" ]; then
  postconf -e mydestination="$MY_DESTINATION"
fi

if [ "$VIRTUAL_ALIAS_DOMAINS" ]; then
  postconf -e mydestination=localhost
  postconf -e virtual_alias_domains="$VIRTUAL_ALIAS_DOMAINS"
  postconf -e virtual_alias_maps="hash:/etc/postfix/virtual"
  postmap /etc/postfix/virtual
fi

if [ "$ROOT_ALIAS" ]; then
  sed -i '/^root:/d' /etc/aliases
  echo "root: $ROOT_ALIAS" >> /etc/aliases
  newaliases
fi

# Postfix smtp runs in a chroot environment so we need to copy the following files in order for it to work
cp /etc/services /var/spool/postfix/etc/services
cp /etc/resolv.conf /var/spool/postfix/etc/resolv.conf

# Start daemon
/usr/sbin/postfix start 

# Attach to a process
tail -fn 0 /var/log/mail.log 

exit 0

