#! /bin/sh

if [ "$MY_HOSTNAME" ]; then
  echo "$MY_HOSTNAME" > /etc/mailname
  postconf -e myhostname="$MY_HOSTNAME"
fi

if [ "$MY_NETWORKS" ]; then
  postconf -e mynetworks="$MY_NETWORKS"
fi

if [ "$MY_DESTINATION" ]; then
  postconf -e mydestination="$MY_DESTINATION"
fi

if [ "$VIRTUAL_ALIAS_DOMAINS" ]; then
  postconf -e virtual_alias_domains="$VIRTUAL_ALIAS_DOMAINS"
  postconf -e virtual_alias_maps="hash:/etc/postfix/virtual"
  postconf -e mydestination=
fi

if [ "$ROOT_ALIAS" ]; then
  sed -i '/^root:/d' /etc/aliases
  echo "root: $ROOT_ALIAS" >> /etc/aliases
  newaliases
fi


# We have to start and stop postfix first through init.d to populate
# postfix spool directory for chroot in which postfix is running.

/etc/init.d/postfix start
/etc/init.d/postfix abort

exec /usr/lib/postfix/sbin/master -c /etc/postfix -d 2>&1
